/**
 * Markdown projection of one folded task report. Pure: every value it writes
 * comes from its input, so the same log window and path always render the same
 * document.
 */
import type { TaskReportFoldResult } from './fold.ts'

/** Everything the Markdown document states. */
export interface TaskReportRenderInput {
  readonly turn: number
  /** How the turn ended, as `turn/end` recorded it. */
  readonly reason: string
  /** Workspace-relative path the document is written to. */
  readonly path: string
  /** ISO timestamp of this generation. */
  readonly generatedAt: string
  readonly result: TaskReportFoldResult
}

/**
 * Render one task report as Markdown.
 * @param input - turn identity, destination path, timestamp, and fold result.
 * @returns the complete document, ending with one newline.
 */
export function renderTaskReport(input: TaskReportRenderInput): string {
  const { result } = input
  const lines: string[] = [
    `# Task report — turn ${input.turn}`,
    '',
    `- **Turn:** ${input.turn} (${input.reason})`,
    `- **Report:** \`${inline(input.path)}\``,
    `- **Generated:** ${input.generatedAt}`,
    '',
    '## Request',
    '',
    result.request ?? '_No user request was recorded for this turn._',
    '',
    '## Summary',
    '',
    result.summary ?? '_The turn produced no closing message._',
    '',
    `## Changes (${result.changes.length})`,
    '',
  ]

  if (result.changes.length === 0) {
    lines.push('_No file change was recorded for this turn._')
  } else {
    lines.push('| File | Change | Lines |', '| --- | --- | --- |')
    for (const change of result.changes) {
      lines.push(`| \`${inline(change.path)}\` | ${change.kind} | +${change.added} / -${change.removed} |`)
    }
  }

  lines.push('', `## Verification (${result.verification.length})`, '')
  if (result.verification.length === 0) {
    lines.push('_No verification command ran in this turn._')
  } else {
    lines.push('| Command | Result |', '| --- | --- |')
    for (const entry of result.verification) {
      const exit = entry.exitCode === undefined ? '' : ` (exit ${entry.exitCode})`
      lines.push(`| \`${inline(entry.command)}\` | ${entry.status}${exit} |`)
    }
  }

  lines.push('', '-----', '', '_Generated by dsh-task-report from this Session log._', '')
  return lines.join('\n')
}

/** Make one value safe inside an inline code span and a table cell. */
function inline(value: string): string {
  return value.replaceAll('`', "'").replaceAll('|', '\\|')
}
